import type { Metadata } from "next";
//import { Geist, Geist_Mono } from "next/font/google";
import DynamicHeader from "../components/Header/DynamicHeader";
import Footer from "../components/Footer/Footer";
import { Providers } from "./providers";
import scss from "./layout.module.scss";
import "../styles/globals.css"; //needed to be removed later, after all tailwind styles will be replaced!

/* const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
}); */

export const metadata: Metadata = {
  title: "DataBase",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => {
  return (
    <html lang="en">
      <body className={scss.main}>
        <Providers>
          <header style={{ gridArea: "header" }}>
            <DynamicHeader />
          </header>
          <main
            style={{
              gridArea: "main",
              padding: "0 24px",
              overflow: "auto",
              position: "relative",
            }}
          >
            {children}
          </main>
          <footer style={{ gridArea: "footer" }}>
            <Footer />
          </footer>
        </Providers>
      </body>
    </html>
  );
};

export default RootLayout;
